apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudera.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudera.name" . }}
    helm.sh/chart: {{ include "cloudera.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 80
      name: 80tcp00
    - port: 2181
      name: 2181tcp00
    - port: 7180
      name: 7180tcp00
    - port: 8020
      name: 8020tcp00
    - port: 8022
      name: 8022tcp00
    - port: 8088
      name: 8088tcp00
    - port: 8888
      name: 8888tcp00
    - port: 8090
      name: 8090tcp00
    - port: 9092
      name: 9092tcp00
    - port: 11000
      name: 11000tcp00
    - port: 18088
      name: 18088tcp00
    - port: 19888
      name: 19888tcp00
    - port: 21050
      name: 21050tcp00
    - port: 25010
      name: 25010tcp00
    - port: 25020
      name: 25020tcp00
    - port: 50010
      name: 50010tcp00
    - port: 50020
      name: 50020tcp00
    - port: 50070
      name: 50070tcp00
    - port: 50075
      name: 50075tcp00
    - port: 60000
      name: 60000tcp00
    - port: 60010
      name: 60010tcp00
  selector:
    app.kubernetes.io/name: {{ include "cloudera.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: '{{ include "cloudera.fullname" . }}-nodeport'
  labels:
    app.kubernetes.io/name: {{ include "cloudera.name" . }}
    helm.sh/chart: {{ include "cloudera.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: 7180tcp1
      port: {{ .Values.service.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

    - name: 80tcp1
      port: {{ .Values.service.port80 }}
      {{- if .Values.service.nodePort80 }}
      nodePort: {{ .Values.service.nodePort80 }}
      {{- end }}

  selector:
    app.kubernetes.io/name: {{ include "cloudera.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}


